[[task]]
  id = "test"
  description = "Run all go tests"
  type = "short"
  cmd = "go test -v ./..."

[[task]]
  id = "migrate"
  type = "group"
  dependencies = ["ent/migrate/apply"]

[[task]]
  id = "schemagen"
  type = "short"
  cmd = """
    echo "Generating schema..."
    go generate ./...
  """

[[task]]
  id = "serve"
  type = "long"
  dependencies = ["schemagen"]
  triggers = ["expl/build"]
  cmd = """
    echo "Starting jsrv server..."
    go run ./jsrv/*.go serve -db-dsn "file:ent/migrate/file.db?mode=rwc&cache=shared&_fk=1" -u expl
  """

  [[task]]
  id = "dev"
  type = "long"
  dependencies = ["serve"]
  cmd = """
    echo "Starting dev server..."
  """

