[[task]]
  id = "migrate/man"
  type = "short"
  cmd = """
  atlas migrate new MANUAL_MIGRATION \
    --dir "file://ent/migrate/migrations"
  """

[[task]]
  id = "migrate/hash"
  type = "short"
  cmd = """
  atlas migrate hash \
    --dir "file://ent/migrate/migrations"
  """

[[task]]
  id = "migrate/gen"
  type = "short"
  cmd = """
  atlas migrate diff GENERATED_MIGRATION \
    --dir "file://ent/migrate/migrations" \
    --to "ent://ent/schema" \
    --dev-url "sqlite://file?mode=memory&_fk=1"
  """

[[task]]
  id = "migrate/apply/dev"
  type = "short"
  cmd = """
  atlas migrate apply   
    --dir "file://ent/migrate/migrations"   
    --url "sqlite://file?mode=memory&_fk=1"
  """

[[task]]
  id = "migrate/apply/prod"
  type = "short"
  cmd = """
  atlas migrate apply   
    --dir "file://ent/migrate/migrations"   
    --url "sqlite://file.db?_fk=1"
  """

[[task]]
  id = "test"
  type = "short"
  cmd = "go test ./... -v"

[[task]]
  id = "generate"
  type = "short"
  cmd = "go generate ./..."

[[task]]
  id = "build"
  type = "short"
  cmd = "cd expl && npm run lint && npm run build"

[[task]]
  id = "update"
  type = "short"
  dependencies = ["build"]
  cmd = """
  rm -rf jsrv/expl
  mkdir jsrv/expl
  cp -r expl/build/* jsrv/expl
  """

[[task]]
  id = "serve"
  type = "long"
  cmd = """
  echo "running dev server"
  go run ./jsrv/*.go serve -db-dsn "file:file.db?mode=rwc&cache=shared&_fk=1" -u expl
  """