[[task]]
  id = "test"
  type = "short"
  cmd = "go test ./... -v"

[[task]]
  id = "migrate"
  type = "group"
  dependencies = ["ent/migrate/apply"]

[[task]]
  id = "generate"
  type = "short"
  cmd = "go generate ./..."

[[task]]
  id = "build"
  type = "short"
  triggers = ["expl/build"]
  cmd = """
    echo "Building jsrv..."
    rm -rf jsrv/expl
    mkdir jsrv/expl
    cp -r expl/build/* jsrv/expl
  """
  
[[task]]
  id = "serve"
  type = "long"
  triggers = ["build"]
  cmd = """
    echo "Starting jsrv server..."
    go run ./jsrv/*.go serve -db-dsn "file:file.db?mode=rwc&cache=shared&_fk=1" -u expl
  """

  [[task]]
  id = "dev"
  type = "long"
  dependencies = ["serve", "migrate"]
  cmd = """
    echo "Starting dev server..."
  """

