// Code generated by EntKit. DO NOT EDIT.
// ---------------------------------------------------------
//
// Copyright (C) 2023 EntKit. All Rights Reserved.
//
// This code is part of the EntKit library and is generated
// automatically to ensure optimal functionality and maintainability.
// Any changes made directly to this file may be overwritten
// by future code generation, leading to unexpected behavior.
//
// Please refer to the EntKit documentation for instructions on
// how to modify the library, extend its functionality or contribute
// to the project: https://entkit.com
// ---------------------------------------------------------

export const CategorySorterEnums = {
    name: "NAME",
};
export const ClueSorterEnums = {
    question: "QUESTION",
    answer: "ANSWER",
    categoryID: "CATEGORY_ID",
    gameID: "GAME_ID",
};
export const GameSorterEnums = {
    show: "SHOW",
    airdate: "AIR_DATE",
    tapedate: "TAPE_DATE",
    seasonID: "SEASON_ID",
};
export const SeasonSorterEnums = {
    number: "NUMBER",
    startdate: "START_DATE",
    enddate: "END_DATE",
};
