// Code generated by EntKit. DO NOT EDIT.
// ---------------------------------------------------------
//
// Copyright (C) 2023 EntKit. All Rights Reserved.
//
// This code is part of the EntKit library and is generated
// automatically to ensure optimal functionality and maintainability.
// Any changes made directly to this file may be overwritten
// by future code generation, leading to unexpected behavior.
//
// Please refer to the EntKit documentation for instructions on
// how to modify the library, extend its functionality or contribute
// to the project: https://entkit.com
// ---------------------------------------------------------

export const CategorySorterEnums = {
    "id": "ID",
    "name": "NAME",
}
export const ClueSorterEnums = {
    "id": "ID",
    "question": "QUESTION",
    "answer": "ANSWER",
    "categoryID": "CATEGORY_ID",
    "gameID": "GAME_ID",
}
export const GameSorterEnums = {
    "id": "ID",
    "show": "SHOW",
    "airDate": "AIR_DATE",
    "tapeDate": "TAPE_DATE",
    "seasonID": "SEASON_ID",
}
export const SeasonSorterEnums = {
    "id": "ID",
    "number": "NUMBER",
    "startDate": "START_DATE",
    "endDate": "END_DATE",
}
