// Code generated by EntKit. DO NOT EDIT.
// ---------------------------------------------------------
//
// Copyright (C) 2023 EntKit. All Rights Reserved.
//
// This code is part of the EntKit library and is generated
// automatically to ensure optimal functionality and maintainability.
// Any changes made directly to this file may be overwritten
// by future code generation, leading to unexpected behavior.
//
// Please refer to the EntKit documentation for instructions on
// how to modify the library, extend its functionality or contribute
// to the project: https://entkit.com
// ---------------------------------------------------------

export type JeppString = string;
export type JeppNumber = number;
export type JeppBoolean = boolean;
export type JeppDate = Date;
export type JeppUUID = string;
export type JeppImage = string;
export type JeppCode = string;
export type JeppURL = string;
export type JeppRichText = string;
export type JeppStringList = JeppString[];
export type JeppNumberList = JeppNumber[];
export type JeppID = JeppUUID | JeppNumber;

interface gqlField<T> {
    edges?: {
        nodes?: Array<T>;
    };
    totalCount?: number;
}

export interface JeppCategoryInterface {
    id: JeppNumber; // int
    name: JeppString; // string
    clues?: JeppClueInterface[];
    _clues?: gqlField<JeppClueInterface>;
}
export interface JeppClueInterface {
    id: JeppNumber; // int
    question: JeppString; // string
    answer: JeppString; // string
    categoryID: JeppNumber; // int
    gameID: JeppNumber; // int
    category?: JeppCategoryInterface;
    game?: JeppGameInterface;
}
export interface JeppGameInterface {
    id: JeppNumber; // int
    show: JeppNumber; // int
    airdate: JeppDate; // time.Time
    tapedate: JeppDate; // time.Time
    seasonID: JeppNumber; // int
    season?: JeppSeasonInterface;
    clues?: JeppClueInterface[];
    _clues?: gqlField<JeppClueInterface>;
}
export interface JeppSeasonInterface {
    id: JeppNumber; // int
    number: JeppNumber; // int
    startdate: JeppDate; // time.Time
    enddate: JeppDate; // time.Time
    games?: JeppGameInterface[];
    _games?: gqlField<JeppGameInterface>;
}
