// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

func (ga *Game) Season(ctx context.Context) (*Season, error) {
	result, err := ga.Edges.SeasonOrErr()
	if IsNotLoaded(err) {
		result, err = ga.QuerySeason().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (s *Season) Games(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *GameOrder, where *GameWhereInput,
) (*GameConnection, error) {
	opts := []GamePaginateOption{
		WithGameOrder(orderBy),
		WithGameFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := s.Edges.totalCount[0][alias]
	if nodes, err := s.NamedGames(alias); err == nil || hasTotalCount {
		pager, err := newGamePager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &GameConnection{Edges: []*GameEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return s.QueryGames().Paginate(ctx, after, first, before, last, opts...)
}
