// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"
)

// CreateSeasonInput represents a mutation input for creating seasons.
type CreateSeasonInput struct {
	Number    int
	StartDate time.Time
	EndDate   time.Time
	GameIDs   []string
}

// Mutate applies the CreateSeasonInput on the SeasonMutation builder.
func (i *CreateSeasonInput) Mutate(m *SeasonMutation) {
	m.SetNumber(i.Number)
	m.SetStartDate(i.StartDate)
	m.SetEndDate(i.EndDate)
	if v := i.GameIDs; len(v) > 0 {
		m.AddGameIDs(v...)
	}
}

// SetInput applies the change-set in the CreateSeasonInput on the SeasonCreate builder.
func (c *SeasonCreate) SetInput(i CreateSeasonInput) *SeasonCreate {
	i.Mutate(c.Mutation())
	return c
}
