// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/ecshreve/jexplore/ent/game"
	"github.com/ecshreve/jexplore/ent/predicate"
	"github.com/ecshreve/jexplore/ent/season"
)

func (gwi *GameWhereInput) ApplySearchQuery(q *string) *GameWhereInput {
	if gwi == nil {
		gwi = &GameWhereInput{}
	}

	if q == nil {
		return gwi
	}

	var orPredicates []predicate.Game
	orPredicates = append(orPredicates, game.IDEQ(*q))
	gwi.AddPredicates(game.Or(orPredicates...))
	return gwi
}

func (swi *SeasonWhereInput) ApplySearchQuery(q *string) *SeasonWhereInput {
	if swi == nil {
		swi = &SeasonWhereInput{}
	}

	if q == nil {
		return swi
	}

	var orPredicates []predicate.Season
	orPredicates = append(orPredicates, season.IDEQ(*q))
	swi.AddPredicates(season.Or(orPredicates...))
	return swi
}
