// Code generated by EntKit. DO NOT EDIT.
// ---------------------------------------------------------
//
// Copyright (C) 2023 EntKit. All Rights Reserved.
//
// This code is part of the EntKit library and is generated
// automatically to ensure optimal functionality and maintainability.
// Any changes made directly to this file may be overwritten
// by future code generation, leading to unexpected behavior.
//
// Please refer to the EntKit documentation for instructions on
// how to modify the library, extend its functionality or contribute
// to the project: https://entkit.com
// ---------------------------------------------------------
import React, { useState } from "react";
import { useShow } from "@refinedev/core";
import * as RA from "@refinedev/antd";
import * as Antd from "antd";
import * as AntdIcons from "@ant-design/icons";

import * as Lists from "./list";
import * as Diagram from "./diagram";
import * as Interfaces from "./typedefs";
import * as View from "./view";
import * as Custom from "./custom";
import * as Action from "./action";

export type GameShowProps = {
    id?: Interfaces.JeppID;
    withEdges?: boolean;
} & RA.ShowProps;
export const GameShow: React.FC<GameShowProps> = ({
    id,
    withEdges,
    ...showProps
}) => {
    const { queryResult } = useShow<Interfaces.JeppGameInterface>({
        resource: "game",
        id,
        metaData: {
            fields: [
                "id",
                "show",
                "airdate",
                "tapedate",
                {
                    season: ["id", "number", "startdate", "enddate"],
                },
            ],
        },
    });

    const { data, isLoading } = queryResult;
    const record = data?.data;

    if (!record) {
        return <></>;
    }

    return (
        <RA.Show
            isLoading={isLoading}
            headerButtons={() => (
                <>
                    <Action.GameListAction recordItemIDs={[record.id]} />
                    <Action.GameEditAction recordItemIDs={[record.id]} />
                    <Action.GameDeleteAction recordItemIDs={[record.id]} />
                </>
            )}
            {...showProps}
        >
            <Antd.Typography.Title level={5}>Id</Antd.Typography.Title>
            <View.JeppStringViewOnShow value={record?.id} />
            <Antd.Typography.Title level={5}>Show</Antd.Typography.Title>
            <View.JeppNumberViewOnShow value={record?.show} />
            <Antd.Typography.Title level={5}>AirDate</Antd.Typography.Title>
            <View.JeppDateViewOnShow value={record?.airdate} />
            <Antd.Typography.Title level={5}>TapeDate</Antd.Typography.Title>
            <View.JeppDateViewOnShow value={record?.tapedate} />

            {withEdges ? (
                <>
                    <Antd.Typography.Title level={3}>
                        Edges
                    </Antd.Typography.Title>
                    <Antd.Descriptions>
                        <Antd.Descriptions.Item label="Season">
                            <View.SeasonBadge {...record?.season} />
                        </Antd.Descriptions.Item>
                    </Antd.Descriptions>
                    <Antd.Tabs defaultActiveKey="0" items={[]} />
                </>
            ) : null}
        </RA.Show>
    );
};

export const GameMainShow: React.FC = () => {
    return <GameShow withEdges={true} />;
};

export const GamePartialShow: React.FC = () => {
    return <GameShow withEdges={false} />;
};

export type SeasonShowProps = {
    id?: Interfaces.JeppID;
    withEdges?: boolean;
} & RA.ShowProps;
export const SeasonShow: React.FC<SeasonShowProps> = ({
    id,
    withEdges,
    ...showProps
}) => {
    const { queryResult } = useShow<Interfaces.JeppSeasonInterface>({
        resource: "season",
        id,
        metaData: {
            fields: [
                "id",
                "number",
                "startdate",
                "enddate",
                {
                    operation: "games",
                    fields: [
                        {
                            edges: [
                                {
                                    node: ["id", "show", "airdate", "tapedate"],
                                },
                            ],
                        },
                        "totalCount",
                    ],
                    variables: {
                        first: 10,
                    },
                },
            ],
        },
    });

    const { data, isLoading } = queryResult;
    const record = data?.data;

    if (!record) {
        return <></>;
    }

    return (
        <RA.Show
            isLoading={isLoading}
            headerButtons={() => (
                <>
                    <Action.SeasonListAction recordItemIDs={[record.id]} />
                    <Action.SeasonEditAction recordItemIDs={[record.id]} />
                    <Action.SeasonDeleteAction recordItemIDs={[record.id]} />
                </>
            )}
            {...showProps}
        >
            <Antd.Typography.Title level={5}>Id</Antd.Typography.Title>
            <View.JeppStringViewOnShow value={record?.id} />
            <Antd.Typography.Title level={5}>Number</Antd.Typography.Title>
            <View.JeppNumberViewOnShow value={record?.number} />
            <Antd.Typography.Title level={5}>StartDate</Antd.Typography.Title>
            <View.JeppDateViewOnShow value={record?.startdate} />
            <Antd.Typography.Title level={5}>EndDate</Antd.Typography.Title>
            <View.JeppDateViewOnShow value={record?.enddate} />

            {withEdges ? (
                <>
                    <Antd.Typography.Title level={3}>
                        Edges
                    </Antd.Typography.Title>
                    <Antd.Descriptions></Antd.Descriptions>
                    <Antd.Tabs
                        defaultActiveKey="0"
                        items={[
                            {
                                label: (
                                    <span>
                                        <AntdIcons.FileOutlined />
                                        Games
                                    </span>
                                ),
                                key: "0",
                                children: (
                                    <Lists.GameList
                                        key={"games-seasons"}
                                        breadcrumb={false}
                                        tableProps={{
                                            extendTable: {
                                                permanentFilter: [
                                                    {
                                                        operator:
                                                            "hasSeasonWith" as any,
                                                        field: "",
                                                        value: {
                                                            id: record?.id,
                                                        },
                                                    },
                                                ],
                                            },
                                        }}
                                    />
                                ),
                            },
                        ]}
                    />
                </>
            ) : null}
        </RA.Show>
    );
};

export const SeasonMainShow: React.FC = () => {
    return <SeasonShow withEdges={true} />;
};

export const SeasonPartialShow: React.FC = () => {
    return <SeasonShow withEdges={false} />;
};
